jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: your-build-command
  include:
    - language: node_js
      node_js:
        - 7
      before_script:
        - npm install
      script: gulp
    - language: bash
      before_script:
        - chmod +x thumbs.sh  # 确保脚本具有可执行权限
      script:
        - ./thumbs.sh

    - language: ruby
      rvm:
        - 2.2
      script: "bundle exec jekyll build"